version: "3.9"

name: mina
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./app:/app
            - ./home:/root
